### ISSUE TITLE
ast.is_null() error when comparing two dynamic variables

### ISSUE THREAD

**Issue by rlkelly** [prove-rs/z3.rs#129]
I'm getting an error `assertion failed: !ast.is_null()`  when running this code:

```
let cfg = Config::new();
let ctx = &Context::new(&cfg);
let x: ast::Dynamic = ast::Bool::new_const(ctx, "a").into();
let y: ast::Dynamic = ast::String::from_str(ctx, "a").unwrap().into();
x._eq(&y);
```

How should this be handled?

**Comment by sameer** [comment]
What are you trying to do with that example code? Is the question about how to handle comparison between dynamic nodes that don't have the same sort?

On Wed, Mar 3, 2021, at 20:26, Rob Kelly wrote:
> 

> I'm getting an error `assertion failed: !ast.is_null()` when running this code:

> `let cfg = Config::new();
let ctx = &Context::new(&cfg);
let x: ast::Dynamic = ast::Bool::new_const(ctx, "a").into();
let y: ast::Dynamic = ast::String::new_const(ctx, "a").into();
x._eq(&y);
`

**Comment by rlkelly** [comment]
I'm curious if you think this could potentially return a `Result` or at least a more verbose error message, or if that should be handled by application logic?

**Comment by sameer** [comment]
> panicking with an error message indicating their types would be much easier to interpret

I think that's a good plan. Assertions made in z3_rs should have error messages with some hints as to what went wrong, and the conditions in which they occur should be called out in docs.

In this case it's because `Ast::_eq` does not return a result so there's a panic for the sake of interface parity. I think that's a fair design decision since the user knows that these are dynamic and they may not have the same sort. But that possibility should be made clear.
