### ISSUE TITLE
SortDiffers error/power should return Real instead of Int

### ISSUE THREAD

**Issue by skius** [prove-rs/z3.rs#163]
A recent update to Z3 changed the returned sort in the `(Int, Int)` power function - it is now `Real` instead of `Int`: https://github.com/Z3Prover/z3/issues/5243

This leads to me getting a `SortDiffers` error, that is obfuscated by the Rust types: I must convert the result of power, a Rust-`Int` but Z3-`Real`, into a Rust-`Real`, such that I may call the Rust-`Real::to_int` function to obtain an aligned Rust- *and* Z3-`Int`, because `Int::to_int` is obviously non-existent.

I assume this has gotten past testing because of Z3's implicit casting on numeric ops; the error appears only e.g. for `(= 1 (^ 2 0))`, because `=` does not do implicit casting and complains that the `1` is an `Int` while `2^0` is a `Real`.

I don't have too much time at the moment, but I could look into making a PR (if no one else wants to) where I might address the following:
- Change the return type of `Int::power` to `Real`
- Add tests for this

Also, I wouldn't know how/where to do this, but it might be a good idea to sprinkle in a few debug asserts in various places that ensure the Rust and Z3 sorts are aligned?

**Comment by jklmnn** [comment]
The reason for the change is that powers may be real types if the exponent is negative. So the new behavior is the correct one (see https://github.com/Z3Prover/z3/issues/5623). Also the change was introduced into 4.8.10 so 4.8.9 should still work. The correct fix would be to let power(Int, Int) return Real instead of Int. Furthermore I guess it would make sense to pin this binding to a specific version of Z3.

**Comment by Pat-Lafon** [comment]
I believe this was fixed in #240
